export function languages() {
    return {
        // SPANISH
        esp: {
            emailinsert: [
                "Si quieres compartir recetas ..",
                ".. añade tu correo electronico",
                "¡Envia!",
                "Código de verificación",
                "¡Cheque!",
                "¡Dirección de correo electrónico no válida!",
                "Correo electrónico enviado con éxito.",
                "Correo electrónico verificado, ¡ahora puedes disfrutar compartiendo recetas!",
                "<p> Este mensaje se ha enviado desde <strong> My Recipes </strong> para verificar su dirección de correo electrónico. </p> <p> Si no solicitó esta verificación, ignórela. </p> <h2> El código de verificación es: </h2> "
            ],
            recipesnavbar: [
                "Salir",
                "Mi perfil"
            ],
            chefprofile: [
                "Cambia/Añade tu imagen",
                "¡Añade!",
                "¡Cambia!",
                "¡Anula!"
            ],
            homepage: [
                "Recetas de los Masovaires",
                "¡Bienvenid@!",
                "Libro de Recetas!",
                "Buscar",
                "Busca entre las recetas",
                "Añadir",
                "Añade tu receta de familia",
                "Últimas recetas añadidas:",
                "Copyright 2020 Renato",
                "Perfil",
                "Cambia/Añade tu imagen",
            ],
            addrecipe: [
                "Nombre receta*:",
                "¿Como se llama tu receta?",
                "Tu nombre",
                "¿Quien és el chef?",
                "Tipo de plato*:",
                "entrante",
                "primero",
                "segundo",
                "acompañamiento",
                "postre",
                "plato único",
                "Personas: (opcional)",
                "¿Para cuantas personas?",
                "Ingredientes*:",
                "Ingrediente nr. ",
                "Cantitad",
                "¡Añade ingrediente! ",
                "Preparación*:",
                "¿Como se hace?",
                "Foto(s)*: (al menos una)",
                "¡Añade foto(s)! ",
                `¿Estás seguro que quieres eliminar esta foto?`,
                "¡Añade!",
                "¡Cambia!",
                "¡Anula!"
            ],
            listall: [
                "Busca receta por:",
                "Cocinero:",
                "todos los cocineros",
                "Nombre receta:",
                "Ingredientes:",
                "Típo de plato:",
                "todos los platos",
                "entrante",
                "primero",
                "segundo",
                "acompañamiento",
                "postre",
                "plato único",
                "NINGUN RESULTADO",
                "Ordena por:",
                "FILTRO ACTIVO",
                "Actualización:"
            ],
            recipecard: [
                "¿Estás seguro que quieres eliminar la receta ",
                "Un ",
                " de: ",
                "Para ",
                " personas.",
                "Ingredientes",
                "Preparación",
                "entrante",
                "primero",
                "segundo",
                "acompañamiento",
                "postre",
                "plato único",
                "Esta receta gusta a ",
                " persona."
            ],
            recipetable: [
                "Ingrediente",
                "Cantidad",
                `¿Estás seguro que quieres eliminar este ingrediente?`
            ]
        },
        //ENGLISH
        eng: {
            emailinsert: [
                "If you want to share recipes, please ..",
                ".. add your e-mail address",
                "Send email!",
                "Insert verification code",
                "Verify!",
                "Invalid email address!",
                "Email sent successfully.",
                "Email verified, now you can enjoy sharing recipes!",
                "<p>This message has been sent from <strong>My Recipes</strong>, to verify your email address.</p><p>If you didn't ask for this verification, please ignore it.</p><h2>Verification code is:</h2>"
            ],
            recipesnavbar: [
                "Log Out",
                "My profile"
            ],
            chefprofile: [
                "Change/Add your image",
                "Add!",
                "Change!",
                "Cancel!"
            ],
            homepage: [
                "Family's Recipes",
                "Welcome!",
                "Recipes' book!",
                "Search",
                "Search among the recipes",
                "Add",
                "Add your family's recipe",
                "Last added recipes:",
                "Copyright 2020 Renato",
                "Profile",
                "Change/Add your image",
            ],
            addrecipe: [
                "Recipe name*:",
                "What's your recipe's name?",
                "Your name",
                "Who is the chef?",
                "Type of plate*:",
                "starter",
                "first course",
                "second course",
                "accompaniment",
                "dessert",
                "single plate",
                "People: (optional)",
                "For how many people?",
                "Ingredients*:",
                "Ingredient nr.",
                "Quantity",
                "Add ingredient!",
                "Preparation*:",
                "How is it done?",
                "Photo(s)*: (at least one",
                "Add photo(s)!",
                `Are you sure you want to delete this photo?`,
                "Add!",
                "Change!",
                "Cancel!"
            ],
            listall: [
                "Search recipe by:",
                "Cooker:",
                "all cookers",
                "Recipe's name:",
                "Ingredients:",
                "Type of dish:",
                "all dishes",
                "starter",
                "first course",
                "second course",
                "accompaniment",
                "dessert",
                "single plate",
                "NO RESULT",
                "Sort by:",
                "ACTIVE FILTER",
                "Update:"
            ],
            recipecard: [
                "Are you sure you want to delete the recipe ",
                "A ",
                " from: ",
                "For ",
                " people.",
                "Ingredients",
                "Preparation",
                "starter",
                "first course",
                "second course",
                "accompaniment",
                "dessert",
                "single plate",
                "This recipe likes to ",
                " people."
            ],
            recipetable: [
                "Ingredient",
                "Quantity",
                `Are you sure you want to delete this ingredient?`
            ],
        },
        //ITALIAN
        ita: {
            emailinsert: [
                "Se vuoi condividere ricette ..",
                ".. aggiungi la tua e-mail",
                "Invia email!",
                "Inserisci il codice di verifica",
                "Verifica!",
                "Indirizzo email non valido!",
                "Email inviata correttamente.",
                "Email verificata, ora puoi divertirti a condividere le ricette!",
                "<p> Questo messaggio è stato inviato da <strong> My Recipes </strong>, per verificare il tuo indirizzo email. </p> <p> Se non hai richiesto questa verifica, per favore ignoralo. </p> <h2> Il codice di verifica è: </h2> "
            ],
            recipesnavbar: [
                "Esci",
                "Mio profilo"
            ],
            chefprofile: [
                "Cambia/Aggiungi foto",
                "Aggiungi!",
                "Aggiorna!",
                "Annulla!"
            ],
            homepage: [
                "Ricette di famiglia",
                "Benvenut@!",
                "Ricettario!",
                "Cerca",
                "Cerca tra le ricette presenti",
                "Aggiungi",
                "Aggiungi la tua ricetta di famiglia",
                "Ultime ricette aggiunte:",
                "Copyright 2020 Renato",
                "Profilo",
                "Cambia/Aggiungi foto",
            ],
            addrecipe: [
                "Nome ricetta*:",
                "Come si chiama la tua ricetta?",
                "Il tuo nome",
                "Chi è lo chef?",
                "Tipo di piatto*:",
                "antipasto",
                "primo",
                "secondo",
                "contorno",
                "dolce",
                "piatto unico",
                "Persone: (opzionale)",
                "Per quante persone?",
                "Ingredienti*:",
                "Ingrediente n.",
                "Quantità",
                "Aggiungi ingrediente!",
                "Preparazione*:",
                "Come si fa?",
                "Foto*: (almeno una)",
                "Aggiungi foto!",
                "Sei sicuro di voler eliminare questa foto?",
                "Aggiungi!",
                "Aggiorna!",
                "Annulla!"
            ],
            listall: [
                "Cerca ricetta per:",
                "Cuoco:",
                "tutti i cuochi",
                "Nome ricetta:",
                "Ingredienti:",
                "Tipo di piatto:",
                "tutti i piatti",
                "antipasto",
                "primo",
                "secondo",
                "contorno",
                "dolce",
                "piatto unico",
                "NESSUN RISULTATO",
                "Ordina per:",
                "FILTRO ATTIVO",
                "Aggiornamento"
            ],
            recipecard: [
                "Sei sicuro di voler eliminare la ricetta ",
                "Un ",
                " di: ",
                "Per ",
                " persone.",
                "Ingredienti",
                "Preparazione",
                "antipasto",
                "primo",
                "secondo",
                "contorno",
                "dolce",
                "piatto unico",
                "Questa ricetta piace a ",
                " persona."
            ],
            recipetable: [
                "Ingrediente",
                "Quantità",
                "Sei sicuro di voler eliminare questo ingrediente?",
            ],
        },
        cat: {
            emailinsert: [
                "Si vols compartir receptes ..",
                ".. afegeix el teu correu electrònic",
                "¡Envia!",
                "Introduïu el codi de verificació",
                "Comproveu!",
                "¡Adreça de correu electrònic no vàlida!",
                "S'ha enviat el correu electrònic correctament.",
                "Verificat per correu electrònic, ara podeu gaudir de compartir receptes!",
                "<p> Aquest missatge s'ha enviat des de <strong> My Recipes </strong>, per verificar la vostra adreça de correu electrònic. </p> <p> Si no heu sol·licitat aquesta verificació, ignora-la. </p> <h2> El codi de verificació és: </h2> "
            ],
            recipesnavbar: [
                "Sortir",
                "El meu perfil"
            ],
            chefprofile: [
                "Canvia/Afegeix la teva imatge",
                "¡Afegeix!",
                "¡Canvia!",
                "¡Anul·la!"
            ],
            homepage: [
                "Receptes dels Masovaires",
                "Benvingut!",
                "Llibre de Receptes!",
                "Cerca",
                "Cerca entre les receptes",
                "Afegeix",
                "Afegeix la teva recepta de família",
                "Últimes receptes afegides:",
                "Copyright 2020 Renato",
                "Perfil",
                "Canvia/Afegeix la teva imatge",
            ],
            addrecipe: [
                "Nom recepta*:",
                "¿Com es diu la teva recepta?",
                "El teu nom",
                "¿Qui és el xef?",
                "Tipu de plat*:",
                "entrant",
                "primer",
                "segon",
                "acompanyament",
                "postres",
                "plat únic",
                "Persones: (opcional)",
                "¿Per quantes persones?",
                "Ingredients*:",
                "Ingredient nr.",
                "Cantitat",
                "Afegeix ingredient!",
                "Preparació*:",
                "¿Com es fa?",
                "Foto(s)*: (almenys una)",
                "Afegeix foto(s)!",
                `Estàs segur que vols eliminar aquesta foto?`,
                "¡Afegeix!",
                "¡Canvia!",
                "¡Anul·la!"
            ],
            listall: [
                "Cerca recepta per:",
                "Cuiner:",
                "tots els cuiners",
                "Nom recepta:",
                "Ingredients:",
                "Típus de plat:",
                "tots els plats",
                "entrant",
                "primer",
                "segon",
                "acompanyament",
                "postres",
                "plat únic",
                "CAP RESULTAT",
                "Ordena por:",
                "FILTRE ACTIU",
                "Actualització:"
            ],
            recipecard: [
                "Estàs segur que vols eliminar la recepta ",
                "Un ",
                " de: ",
                "Per ",
                " persones.",
                "Ingredients",
                "Preparació",
                "entrant",
                "primer",
                "segon",
                "acompanyament",
                "postres",
                "plat únic",
                "Aquesta recepta agrada a ",
                " persona."
            ],
            recipetable: [
                "Ingredient",
                "Quantitat",
                `Estàs segur que vols eliminar aquest ingredient?`,
            ]
        }
    }
}

