export function languages() {
    return {
        // SPANISH
        esp: {
            recipesnavbar: [
                "Idioma:"
            ],
            homepage: [
                "Recetas de los Masovaires",
                "¡Bienvenid@s a nuestro",
                "Libro de Recetas!",
                "Buscar",
                "Busca entre las recetas",
                "Añadir",
                "Añade tu receta de familia"
            ],
            addrecipe: [
                "Nombre receta*:",
                "¿Como se llama tu receta?",
                "Tu nombre",
                "¿Quien és el chef?",
                "Tipo de plato*:",
                "entrante",
                "primero",
                "segundo",
                "acompañamiento",
                "postre",
                "plato único",
                "Personas: (opcional)",
                "¿Para cuantas personas?",
                "Ingredientes*:",
                "Ingrediente nr. ",
                "Cantitad",
                "¡Añade ingrediente! ",
                "Preparación*:",
                "¿Como se hace?",
                "Foto(s)*: (al menos una)",
                "¡Añade foto(s)! ",
                `¿Estás seguro que quieres eliminar esta foto?`,
                "¡Añade!",
                "¡Cambia!",
                "¡Anula!"
            ],
            listall: [
                "Busca receta por:",
                "cocinero:",
                "todos los cocineros",
                "nombre receta:",
                "ingredientes:",
                "típo de plato:",
                "todos los platos",
                "entrante",
                "primero",
                "segundo",
                "acompañamiento",
                "postre",
                "plato único",
                "NINGUN RESULTADO"
            ],
            recipecard: [
                "¿Estás seguro que quieres eliminar la receta ",
                "Un ",
                " de: ",
                "Para ",
                " personas.",
                "Ingredientes",
                "Preparación",
                "entrante",
                "primero",
                "segundo",
                "acompañamiento",
                "postre",
                "plato único",
                "Esta receta gusta a ",
                " persona."
            ],
            recipetable: [
                "Ingrediente",
                "Cantidad",
                `¿Estás seguro que quieres eliminar este ingrediente?`
            ]
        },
        //ENGLISH
        eng: {
            recipesnavbar: [
                "Language:"
            ],
            homepage: [
                "Family's Recipes",
                "Welcome to our",
                "Recipes' book!",
                "Search",
                "Search among the recipes",
                "Add",
                "Add your family's recipe"
            ],
            addrecipe: [
                "Recipe name*:",
                "What's your recipe's name?",
                "Your name",
                "Who is the chef?",
                "Type of plate*:",
                "starter",
                "first course",
                "second course",
                "accompaniment",
                "dessert",
                "single plate",
                "People: (optional)",
                "For how many people?",
                "Ingredients*:",
                "Ingredient nr.",
                "Quantity",
                "Add ingredient!",
                "Preparation*:",
                "How is it done?",
                "Photo(s)*: (at least one",
                "Add photo(s)!",
                `Are you sure you want to delete this photo?`,
                "Add!",
                "Change!",
                "Cancel!"
            ], // {language [31]}
            listall: [
                "Search recipe by:",
                "cooker:",
                "all cookers",
                "recipe's name:",
                "ingredients:",
                "type of dish:",
                "all dishes",
                "starter",
                "first course",
                "second course",
                "accompaniment",
                "dessert",
                "single plate",
                "NO RESULT"
            ],
            recipecard: [
                "Are you sure you want to delete the recipe ",
                "A ",
                " from: ",
                "For ",
                " people.",
                "Ingredients",
                "Preparation",
                "starter",
                "first course",
                "second course",
                "accompaniment",
                "dessert",
                "single plate",
                "This recipe likes to ",
                " people."
            ],
            recipetable: [
                "Ingredient",
                "Quantity",
                `Are you sure you want to delete this ingredient?`
            ],
        },
        //ITALIAN
        ita: {
            recipesnavbar: [
                "Lingua:"
            ],
            homepage: [
                "Ricette di famiglia",
                "Benvenut@ nel nostro",
                "Ricettario!",
                "Cerca",
                "Cerca tra le ricette presenti",
                "Aggiungi",
                "Aggiungi la tua ricetta di famiglia"
            ],
            addrecipe: [
                "Nome ricetta*:",
                "Come si chiama la tua ricetta?",
                "Il tuo nome",
                "Chi è lo chef?",
                "Tipo di piatto*:",
                "antipasto",
                "primo",
                "secondo",
                "contorno",
                "dolce",
                "piatto unico",
                "Persone: (opzionale)",
                "Per quante persone?",
                "Ingredienti*:",
                "Ingrediente n.",
                "Quantità",
                "Aggiungi ingrediente!",
                "Preparazione*:",
                "Come si fa?",
                "Foto*: (almeno una)",
                "Aggiungi foto!",
                "Sei sicuro di voler eliminare questa foto?",
                "Aggiungi!",
                "Aggiorna!",
                "Annulla!"
            ],
            listall: [
                "Cerca ricetta per:",
                "cuoco",
                "tutti i cuochi",
                "nome ricetta:",
                "ingredienti",
                "tipo di piatto:",
                "tutti i piatti",
                "antipasto",
                "primo",
                "secondo",
                "contorno",
                "dolce",
                "piatto unico",
                "NESSUN RISULTATO"
            ],
            recipecard: [
                "Sei sicuro di voler eliminare la ricetta ",
                "Un ",
                " di: ",
                "Per ",
                " persone.",
                "Ingredienti",
                "Preparazione",
                "antipasto",
                "primo",
                "secondo",
                "contorno",
                "dolce",
                "piatto unico",
                "Questa ricetta piace a ",
                " persona."
            ],
            recipetable: [
                "Ingrediente",
                "Quantità",
                "Sei sicuro di voler eliminare questo ingrediente?",
            ],
        },
        cat: {
            recipesnavbar: [
                "Idioma:"
            ],
            homepage: [
                "Receptes dels Masovaires",
                "Benvinguts al nostre",
                "Llibre de Receptes!",
                "Cerca",
                "Cerca entre les receptes",
                "Afegeix",
                "Afegeix la teva recepta de família"
            ],
            addrecipe: [
                "Nom recepta*:",
                "¿Com es diu la teva recepta?",
                "El teu nom",
                "¿Qui és el xef?",
                "Tipu de plat*:",
                "entrant",
                "primer",
                "segon",
                "acompanyament",
                "postres",
                "plat únic",
                "Persones: (opcional)",
                "¿Per quantes persones?",
                "Ingredients*:",
                "Ingredient nr.",
                "Cantitat",
                "Afegeix ingredient!",
                "Preparació*:",
                "¿Com es fa?",
                "Foto(s)*: (almenys una)",
                "Afegeix foto(s)!",
                `Estàs segur que vols eliminar aquesta foto?`,
                "¡Afegeix!",
                "¡Canvia!",
                "¡Anul·la!"
            ],
            listall: [
                "Cerca recepta per:",
                "cuiner:",
                "tots els cuiners",
                "nom recepta:",
                "ingredients:",
                "típus de plat:",
                "tots els plats",
                "entrant",
                "primer",
                "segon",
                "acompanyament",
                "postres",
                "plat únic",
                "CAP RESULTAT"
            ],
            recipecard: [
                "Estàs segur que vols eliminar la recepta ",
                "Un ",
                " de: ",
                "Per ",
                " persones.",
                "Ingredients",
                "Preparació",
                "entrant",
                "primer",
                "segon",
                "acompanyament",
                "postres",
                "plat únic",
                "Aquesta recepta agrada a ",
                " persona."
            ],
            recipetable: [
                "Ingredient",
                "Quantitat",
                `Estàs segur que vols eliminar aquest ingredient?`,
            ]
        }
    }
}

